# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_currency', models.CharField(max_length=250)),
                ('denominatio', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CoinsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('monetary_units', models.CharField(max_length=250)),
            ],
        ),
    ]
