# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0002_auto_20181229_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coins_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='philatelist.CoinsGroups'),
            preserve_default=False,
        ),
    ]
