# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0003_coin_coins_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
                ('used', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StampsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='coin',
            name='coins_group',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='CoinsGroups',
        ),
        migrations.AddField(
            model_name='stamp',
            name='stamp_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='philatelist.StampsGroup'),
        ),
    ]
