# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0005_stamp_is_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsgroup',
            name='image',
            field=models.CharField(default=-1, max_length=250),
            preserve_default=False,
        ),
    ]
