# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('philatelist', '0006_stampsgroup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampsgroup',
            name='image',
            field=models.CharField(max_length=4000),
        ),
    ]
