# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_currency', models.CharField(max_length=250)),
                ('denomination', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CoinsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('monetary_units', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='coins_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numismatist.CoinsGroups'),
        ),
    ]
